### ISSUE TITLE
Question: Is this proper if I just want to parse the entire file?

### ISSUE THREAD

**Issue by molikto** [JetBrains/jsitter#4]
Thanks for jsitter!

So my question is if I just want to parse a file using TreeSitter parse.c entirely, and don't need to keep the tree afterwards. Shoud I use this lib & Zipper API? Because I think the Zipper API will have some JVM object allocation. 

Alternative will be:

Read the file entirely to a DirectByteBuffer, parse in C, put result { sym, start, end } of the named tree nodes in depth first traversal order. Reconstruct the AST in Java. This is to avoid too much JNI calls, because it is supposed to be expsensive.

**Comment by zajac** [comment]
Hi!
It is up to you, what to use, here is just some information about jsitter
* Zippers don't use JNI. jsitter reads native memory of the trees directly
* Zippers are allocated as you walk. Most of them are young garbage, but the path from the root to current location is retained in memory.
* parser reads data from jsitter.Text in chunks into native memory for parsing and then comes back for more if there are any. One can provide a custom jsitterText impl

**Comment by molikto** [comment]
@zajac thanks! Another problem I got is I don't know what the subtree API actually is. I ended up using what I described, for the test file I am using, TreeSitter uses ~40ms to parse it. And then recursing all information using Cursor API uses ~10ms, then in the JVM reparse the tree to AST use ~60ms. I think this is currently OK with my usecase...

**Comment by zajac** [comment]
* Subtree API is an actual tree-sitter tree data layout. (Internal API)
* try tweaking READING_BUFFER_CAPACITY in jsitter.impl if you want to have larger chunks read into native memory at once. (that is probably the reason of that 20ms difference)
